name: Studio Rendezvous
favicon: null
layout_spectrum: 0.38871
typography_spectrum: 0.5429646
title: Studio Rendezvous is testing to see if this works as advertised
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ec4d01'
    - '#ffffff'
    - '#9fb9c7'
    - '#111723'
    - '#535760'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
