name: Studio Rendezvous
favicon: null
layout_spectrum: 0.2046187
typography_spectrum: 0.5429646
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.0625
  lightness: 0.4194415
  saturation: 0
  rhythmicContrast: 0.4205156
purpose: []
