name: Studio Rendezvous
favicon: null
layout_spectrum: 0.2046187
typography_spectrum: 0.5429646
title: Studio Rendezvous is testing to see if this works as advertised
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff5100'
    - '#feb287'
    - '#343434'
    - '#727272'
  brandStrength: 0.0625
  lightness: 0.4194415
  saturation: 0
  rhythmicContrast: 0.4205156
purpose: []
